-- Configuração inicial
SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- Tabela EMPRESA
CREATE TABLE `EMPRESA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_EMPRESA` INT,
  `ID_CONTADOR` INT,
  `RAZAO_SOCIAL` VARCHAR(100),
  `NOME_FANTASIA` VARCHAR(100),
  `CNPJ` VARCHAR(20),
  `INSCRICAO_ESTADUAL` VARCHAR(20),
  `INSCRICAO_ESTADUAL_ST` VARCHAR(20),
  `INSCRICAO_MUNICIPAL` VARCHAR(20),
  `INSCRICAO_JUNTA_COMERCIAL` VARCHAR(20),
  `DATA_INSC_JUNTA_COMERCIAL` DATE,
  `TIPO` VARCHAR(50),
  `DATA_CADASTRO` DATE,
  `DATA_INICIO_ATIVIDADES` DATE,
  `SUFRAMA` VARCHAR(20),
  `EMAIL` VARCHAR(100),
  `IMAGEM_LOGOTIPO` VARCHAR(255),
  `CRT` VARCHAR(50),
  `TIPO_REGIME` VARCHAR(50),
  `CODIGO_IBGE_CIDADE` INT,
  `CODIGO_IBGE_UF` INT,
  `CEI` VARCHAR(20),
  `CODIGO_CNAE_PRINCIPAL` VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FORNECEDOR
CREATE TABLE `FORNECEDOR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT NOT NULL,
  `ID_ATIVIDADE_FOR_CLI` INT NOT NULL,
  `ID_SITUACAO_FOR_CLI` INT NOT NULL,
  `DESDE` DATE,
  `OPTANTE_SIMPLES_NACIONAL` VARCHAR(50),
  `LOCALIZACAO` VARCHAR(50),
  `DATA_CADASTRO` DATE,
  `SOFRE_RETENCAO` VARCHAR(50),
  `CHEQUE_NOMINAL_A` VARCHAR(100),
  `OBSERVACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CLIENTE
CREATE TABLE `CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT NOT NULL,
  `ID_ATIVIDADE_FOR_CLI` INT NOT NULL,
  `ID_SITUACAO_FOR_CLI` INT NOT NULL,
  `DESDE` DATE,
  `DATA_CADASTRO` DATE,
  `OBSERVACAO` TEXT,
  `PORCENTO_DESCONTO` DECIMAL(12,2),
  `LIMITE_CREDITO` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COLABORADOR
CREATE TABLE `COLABORADOR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT NOT NULL,
  `ID_TIPO_COLABORADOR` INT NOT NULL,
  `ID_CARGO` INT NOT NULL,
  `ID_SETOR` INT NOT NULL,
  `MATRICULA` VARCHAR(100),
  `FOTO_34` VARCHAR(255),
  `DATA_CADASTRO` DATE,
  `DATA_ADMISSAO` DATE,
  `PAGAMENTO_FORMA` VARCHAR(50),
  `PAGAMENTO_BANCO` VARCHAR(100),
  `PAGAMENTO_AGENCIA` VARCHAR(100),
  `PAGAMENTO_AGENCIA_DIGITO` VARCHAR(50),
  `PAGAMENTO_CONTA` VARCHAR(100),
  `PAGAMENTO_CONTA_DIGITO` VARCHAR(50),
  `CTPS_NUMERO` VARCHAR(100),
  `CTPS_SERIE` VARCHAR(100),
  `CTPS_DATA_EXPEDICAO` DATE,
  `CTPS_UF` VARCHAR(50),
  `OBSERVACAO` TEXT,
  `DATA_DEMISSAO` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PRODUTO
CREATE TABLE `PRODUTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_UNIDADE_PRODUTO` INT NOT NULL,
  `ID_MARCA_PRODUTO` INT,
  `ID_SUB_GRUPO` INT NOT NULL,
  `GTIN` VARCHAR(50),
  `CODIGO_INTERNO` VARCHAR(100),
  `NCM` VARCHAR(100),
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT,
  `DESCRICAO_PDV` VARCHAR(100),
  `VALOR_COMPRA` DECIMAL(12,2),
  `VALOR_VENDA` DECIMAL(12,2),
  `PRECO_VENDA_MINIMO` DECIMAL(12,2),
  `PRECO_LUCRO_ZERO` DECIMAL(12,2),
  `PRECO_LUCRO_MINIMO` DECIMAL(12,2),
  `PRECO_LUCRO_MAXIMO` DECIMAL(12,2),
  `QUANTIDADE_ESTOQUE` DECIMAL(12,2),
  `QUANTIDADE_ESTOQUE_ANTERIOR` DECIMAL(12,2),
  `ESTOQUE_MINIMO` DECIMAL(12,2),
  `ESTOQUE_MAXIMO` DECIMAL(12,2),
  `ESTOQUE_IDEAL` DECIMAL(12,2),
  `EXCLUIDO` VARCHAR(50),
  `INATIVO` VARCHAR(50),
  `DATA_CADASTRO` DATE,
  `FOTO_PRODUTO` VARCHAR(255),
  `IAT` VARCHAR(50),
  `IPPT` VARCHAR(50),
  `TIPO_ITEM_SPED` VARCHAR(50),
  `TOTALIZADOR_PARCIAL` VARCHAR(100),
  `CODIGO_BALANCA` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela UNIDADE_PRODUTO
CREATE TABLE `UNIDADE_PRODUTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `SIGLA` VARCHAR(100),
  `DESCRICAO` TEXT,
  `PODE_FRACIONAR` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PRODUTO_GRUPO
CREATE TABLE `PRODUTO_GRUPO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CARGO
CREATE TABLE `CARGO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT,
  `SALARIO` DECIMAL(12,2),
  `CBO_1994` VARCHAR(100),
  `CBO_2002` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela SETOR
CREATE TABLE `SETOR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PAIS
CREATE TABLE `PAIS` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` INT,
  `NOME_EN` VARCHAR(100),
  `NOME_PTBR` VARCHAR(100),
  `SIGLA2` VARCHAR(50),
  `SIGLA3` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela UF
CREATE TABLE `UF` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PAIS` INT NOT NULL,
  `SIGLA` VARCHAR(50),
  `NOME` VARCHAR(100),
  `CODIGO_IBGE` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela MUNICIPIO
CREATE TABLE `MUNICIPIO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_UF` INT NOT NULL,
  `NOME` VARCHAR(100),
  `CODIGO_IBGE` INT,
  `CODIGO_RECEITA_FEDERAL` INT,
  `CODIGO_ESTADUAL` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela BANCO
CREATE TABLE `BANCO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(100),
  `NOME` VARCHAR(100),
  `URL` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela AGENCIA_BANCO
CREATE TABLE `AGENCIA_BANCO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_BANCO` INT NOT NULL,
  `CODIGO` VARCHAR(100),
  `DIGITO` VARCHAR(50),
  `NOME` VARCHAR(100),
  `LOGRADOURO` VARCHAR(100),
  `NUMERO` VARCHAR(100),
  `CEP` VARCHAR(100),
  `BAIRRO` VARCHAR(100),
  `MUNICIPIO` VARCHAR(100),
  `UF` VARCHAR(50),
  `TELEFONE` VARCHAR(100),
  `GERENTE` VARCHAR(100),
  `CONTATO` VARCHAR(100),
  `OBSERVACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CEP
CREATE TABLE `CEP` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CEP` VARCHAR(100),
  `LOGRADOURO` VARCHAR(100),
  `COMPLEMENTO` VARCHAR(100),
  `BAIRRO` VARCHAR(100),
  `MUNICIPIO` VARCHAR(100),
  `UF` VARCHAR(50),
  `CODIGO_IBGE_MUNICIPIO` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela OPERADORA_CARTAO
CREATE TABLE `OPERADORA_CARTAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `BANDEIRA` VARCHAR(100),
  `NOME` VARCHAR(100),
  `TAXA_ADM` DECIMAL(12,2),
  `TAXA_ADM_DEBITO` DECIMAL(12,2),
  `VALOR_ALUGUEL_POS_PIN` DECIMAL(12,2),
  `VENCIMENTO_ALUGUEL` INT,
  `FONE1` VARCHAR(100),
  `FONE2` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PRODUTO_SUB_GRUPO
CREATE TABLE `PRODUTO_SUB_GRUPO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_GRUPO` INT NOT NULL,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CONTATO
CREATE TABLE `CONTATO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT,
  `ID_EMPRESA` INT,
  `NOME` VARCHAR(100),
  `EMAIL` VARCHAR(100),
  `FONE_COMERCIAL` VARCHAR(100),
  `FONE_RESIDENCIAL` VARCHAR(100),
  `FONE_CELULAR` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ENDERECO
CREATE TABLE `ENDERECO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_EMPRESA` INT,
  `ID_PESSOA` INT,
  `LOGRADOURO` VARCHAR(100),
  `NUMERO` VARCHAR(100),
  `COMPLEMENTO` VARCHAR(100),
  `BAIRRO` VARCHAR(100),
  `CIDADE` VARCHAR(100),
  `CEP` VARCHAR(100),
  `MUNICIPIO_IBGE` INT,
  `UF` VARCHAR(50),
  `FONE` VARCHAR(100),
  `FAX` VARCHAR(100),
  `PRINCIPAL` VARCHAR(50),
  `ENTREGA` VARCHAR(50),
  `COBRANCA` VARCHAR(50),
  `CORRESPONDENCIA` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela SITUACAO_FOR_CLI
CREATE TABLE `SITUACAO_FOR_CLI` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela TIPO_COLABORADOR
CREATE TABLE `TIPO_COLABORADOR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela USUARIO
CREATE TABLE `USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COLABORADOR` INT NOT NULL,
  `ID_PAPEL` INT NOT NULL,
  `LOGIN` VARCHAR(100),
  `SENHA` VARCHAR(100),
  `DATA_CADASTRO` DATE,
  `ADMINISTRADOR` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PAPEL
CREATE TABLE `PAPEL` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT,
  `ACESSO_COMPLETO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FUNCAO
CREATE TABLE `FUNCAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DESCRICAO_MENU` VARCHAR(100),
  `IMAGEM_MENU` VARCHAR(100),
  `METODO` VARCHAR(100),
  `NOME` VARCHAR(100),
  `FORMULARIO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PAPEL_FUNCAO
CREATE TABLE `PAPEL_FUNCAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PAPEL` INT NOT NULL,
  `ID_FUNCAO` INT NOT NULL,
  `PODE_CONSULTAR` VARCHAR(50),
  `PODE_INSERIR` VARCHAR(50),
  `PODE_ALTERAR` VARCHAR(50),
  `PODE_EXCLUIR` VARCHAR(50),
  `HABILITADO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CNAE
CREATE TABLE `CNAE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(100),
  `DENOMINACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela NCM
CREATE TABLE `NCM` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(100),
  `DESCRICAO` TEXT,
  `OBSERVACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela TRANSPORTADORA
CREATE TABLE `TRANSPORTADORA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT NOT NULL,
  `DATA_CADASTRO` DATE,
  `OBSERVACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CONTADOR
CREATE TABLE `CONTADOR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `INSCRICAO_CRC` VARCHAR(100),
  `UF_CRC` VARCHAR(50),
  `FONE` VARCHAR(100),
  `FAX` VARCHAR(100),
  `LOGRADOURO` VARCHAR(100),
  `NUMERO` VARCHAR(100),
  `COMPLEMENTO` VARCHAR(100),
  `BAIRRO` VARCHAR(100),
  `CIDADE` VARCHAR(100),
  `CEP` VARCHAR(100),
  `MUNICIPIO_IBGE` INT,
  `UF` VARCHAR(50),
  `EMAIL` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela TALONARIO_CHEQUE
CREATE TABLE `TALONARIO_CHEQUE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `TALAO` VARCHAR(100),
  `NUMERO` INT,
  `STATUS_TALAO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CHEQUE
CREATE TABLE `CHEQUE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_TALONARIO_CHEQUE` INT NOT NULL,
  `NUMERO` INT,
  `STATUS_CHEQUE` VARCHAR(50),
  `DATA_STATUS` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PESSOA
CREATE TABLE `PESSOA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100) NOT NULL,
  `TIPO` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100),
  `SITE` VARCHAR(100),
  `CLIENTE` VARCHAR(50),
  `FORNECEDOR` VARCHAR(50),
  `COLABORADOR` VARCHAR(50),
  `TRANSPORTADORA` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PESSOA_FISICA
CREATE TABLE `PESSOA_FISICA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT NOT NULL,
  `ID_ESTADO_CIVIL` INT NOT NULL,
  `CPF` VARCHAR(100),
  `RG` VARCHAR(100),
  `ORGAO_RG` VARCHAR(100),
  `DATA_EMISSAO_RG` DATE,
  `DATA_NASCIMENTO` DATE,
  `SEXO` VARCHAR(50),
  `NATURALIDADE` VARCHAR(100),
  `NACIONALIDADE` VARCHAR(100),
  `RACA` VARCHAR(50),
  `TIPO_SANGUE` VARCHAR(50),
  `CNH_NUMERO` VARCHAR(100),
  `CNH_CATEGORIA` VARCHAR(50),
  `CNH_VENCIMENTO` DATE,
  `TITULO_ELEITORAL_NUMERO` VARCHAR(100),
  `TITULO_ELEITORAL_ZONA` INT,
  `TITULO_ELEITORAL_SECAO` INT,
  `RESERVISTA_NUMERO` VARCHAR(100),
  `RESERVISTA_CATEGORIA` INT,
  `NOME_MAE` VARCHAR(100),
  `NOME_PAI` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PESSOA_JURIDICA
CREATE TABLE `PESSOA_JURIDICA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT NOT NULL,
  `CNPJ` VARCHAR(100),
  `FANTASIA` VARCHAR(100),
  `INSCRICAO_MUNICIPAL` VARCHAR(100),
  `INSCRICAO_ESTADUAL` VARCHAR(100),
  `DATA_CONSTITUICAO` DATE,
  `TIPO_REGIME` VARCHAR(50),
  `CRT` VARCHAR(50),
  `SUFRAMA` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela TIPO_ITEM_SPED
CREATE TABLE `TIPO_ITEM_SPED` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(50),
  `DESCRICAO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ATIVIDADE_FOR_CLI
CREATE TABLE `ATIVIDADE_FOR_CLI` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ESTADO_CIVIL
CREATE TABLE `ESTADO_CIVIL` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela PRODUTO_MARCA
CREATE TABLE `PRODUTO_MARCA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CONTA_CAIXA
CREATE TABLE `CONTA_CAIXA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_AGENCIA_BANCO` INT,
  `CODIGO` VARCHAR(100),
  `DIGITO` VARCHAR(50),
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT,
  `TIPO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDEDOR
CREATE TABLE `VENDEDOR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COLABORADOR` INT,
  `COMISSAO` DECIMAL(12,2),
  `META_VENDAS` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela CFOP
CREATE TABLE `CFOP` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CFOP` INT,
  `DESCRICAO` TEXT,
  `APLICACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_TIPO_REQUISICAO
CREATE TABLE `COMPRA_TIPO_REQUISICAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(50),
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_REQUISICAO
CREATE TABLE `COMPRA_REQUISICAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_TIPO_REQUISICAO` INT NOT NULL,
  `ID_COLABORADOR` INT NOT NULL,
  `DATA_REQUISICAO` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_REQUISICAO_DETALHE
CREATE TABLE `COMPRA_REQUISICAO_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_REQUISICAO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE` DECIMAL(12,2),
  `QUANTIDADE_COTADA` DECIMAL(12,2),
  `ITEM_COTADO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_COTACAO
CREATE TABLE `COMPRA_COTACAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DATA_COTACAO` DATE,
  `DESCRICAO` VARCHAR(100),
  `SITUACAO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_FORNECEDOR_COTACAO
CREATE TABLE `COMPRA_FORNECEDOR_COTACAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_COTACAO` INT NOT NULL,
  `ID_FORNECEDOR` INT NOT NULL,
  `PRAZO_ENTREGA` VARCHAR(100),
  `VENDA_CONDICOES_PAGAMENTO` VARCHAR(100),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `TOTAL` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_COTACAO_DETALHE
CREATE TABLE `COMPRA_COTACAO_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_FORNECEDOR_COTACAO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE` DECIMAL(12,2),
  `QUANTIDADE_PEDIDA` DECIMAL(12,2),
  `VALOR_UNITARIO` DECIMAL(12,2),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_REQ_COTACAO_DETALHE
CREATE TABLE `COMPRA_REQ_COTACAO_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_COTACAO` INT NOT NULL,
  `ID_COMPRA_REQUISICAO_DETALHE` INT NOT NULL,
  `QUANTIDADE_COTADA` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_PEDIDO
CREATE TABLE `COMPRA_PEDIDO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_TIPO_PEDIDO` INT NOT NULL,
  `ID_FORNECEDOR` INT NOT NULL,
  `DATA_PEDIDO` DATE,
  `DATA_PREVISTA_ENTREGA` DATE,
  `DATA_PREVISAO_PAGAMENTO` DATE,
  `LOCAL_ENTREGA` VARCHAR(100),
  `LOCAL_COBRANCA` VARCHAR(100),
  `CONTATO` VARCHAR(100),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL_PEDIDO` DECIMAL(12,2),
  `TIPO_FRETE` VARCHAR(50),
  `FORMA_PAGAMENTO` VARCHAR(50),
  `QUANTIDADE_PARCELAS` INT,
  `DIAS_PRIMEIRO_VENCIMENTO` INT,
  `DIAS_INTERVALO` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_PEDIDO_DETALHE
CREATE TABLE `COMPRA_PEDIDO_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_PEDIDO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE` DECIMAL(12,2),
  `VALOR_UNITARIO` DECIMAL(12,2),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_COTACAO_PEDIDO_DETALHE
CREATE TABLE `COMPRA_COTACAO_PEDIDO_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COMPRA_PEDIDO` INT NOT NULL,
  `ID_COMPRA_COTACAO_DETALHE` INT NOT NULL,
  `QUANTIDADE_PEDIDA` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela COMPRA_TIPO_PEDIDO
CREATE TABLE `COMPRA_TIPO_PEDIDO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(50),
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_ORCAMENTO_CABECALHO
CREATE TABLE `VENDA_ORCAMENTO_CABECALHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_VENDA_CONDICOES_PAGAMENTO` INT NOT NULL,
  `ID_VENDEDOR` INT NOT NULL,
  `ID_TRANSPORTADORA` INT,
  `ID_CLIENTE` INT NOT NULL,
  `TIPO` VARCHAR(50),
  `CODIGO` VARCHAR(100),
  `DATA_CADASTRO` DATE,
  `VALIDADE` DATE,
  `TIPO_FRETE` VARCHAR(50),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `VALOR_FRETE` DECIMAL(12,2),
  `TAXA_COMISSAO` DECIMAL(12,2),
  `VALOR_COMISSAO` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL` DECIMAL(12,2),
  `OBSERVACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela TIPO_NOTA_FISCAL
CREATE TABLE `TIPO_NOTA_FISCAL` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `MODELO` VARCHAR(50),
  `SERIE` VARCHAR(50),
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT,
  `TEMPLATE` TEXT,
  `NUMERO_ITENS` INT,
  `ULTIMO_IMPRESSO` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_ORCAMENTO_DETALHE
CREATE TABLE `VENDA_ORCAMENTO_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_VENDA_ORCAMENTO_CABECALHO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE` DECIMAL(12,2),
  `VALOR_UNITARIO` DECIMAL(12,2),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_CABECALHO
CREATE TABLE `VENDA_CABECALHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_VENDA_ORCAMENTO_CABECALHO` INT,
  `ID_VENDA_CONDICOES_PAGAMENTO` INT NOT NULL,
  `ID_TRANSPORTADORA` INT,
  `ID_TIPO_NOTA_FISCAL` INT NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  `ID_VENDEDOR` INT NOT NULL,
  `DATA_VENDA` DATE,
  `DATA_SAIDA` DATE,
  `HORA_SAIDA` VARCHAR(100),
  `NUMERO_FATURA` INT,
  `LOCAL_ENTREGA` VARCHAR(100),
  `LOCAL_COBRANCA` VARCHAR(100),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_COMISSAO` DECIMAL(12,2),
  `VALOR_COMISSAO` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL` DECIMAL(12,2),
  `TIPO_FRETE` VARCHAR(50),
  `FORMA_PAGAMENTO` VARCHAR(50),
  `VALOR_FRETE` DECIMAL(12,2),
  `VALOR_SEGURO` DECIMAL(12,2),
  `OBSERVACAO` TEXT,
  `SITUACAO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_DETALHE
CREATE TABLE `VENDA_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PRODUTO` INT NOT NULL,
  `ID_VENDA_CABECALHO` INT NOT NULL,
  `QUANTIDADE` DECIMAL(12,2),
  `VALOR_UNITARIO` DECIMAL(12,2),
  `VALOR_SUBTOTAL` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_TOTAL` DECIMAL(12,2),
  `TAXA_COMISSAO` DECIMAL(12,2),
  `VALOR_COMISSAO` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_CONDICOES_PAGAMENTO
CREATE TABLE `VENDA_CONDICOES_PAGAMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(100),
  `DESCRICAO` TEXT,
  `FATURAMENTO_MINIMO` DECIMAL(12,2),
  `FATURAMENTO_MAXIMO` DECIMAL(12,2),
  `INDICE_CORRECAO` DECIMAL(12,2),
  `DIAS_TOLERANCIA` INT,
  `VALOR_TOLERANCIA` DECIMAL(12,2),
  `PRAZO_MEDIO` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_CONDICOES_PARCELAS
CREATE TABLE `VENDA_CONDICOES_PARCELAS` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_VENDA_CONDICOES_PAGAMENTO` INT NOT NULL,
  `PARCELA` INT,
  `DIAS` INT,
  `TAXA` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_FECHAMENTO_CAIXA_BANCO
CREATE TABLE `FIN_FECHAMENTO_CAIXA_BANCO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `DATA_FECHAMENTO` DATE,
  `MES_ANO` VARCHAR(100),
  `MES` VARCHAR(50),
  `ANO` VARCHAR(50),
  `SALDO_ANTERIOR` DECIMAL(12,2),
  `RECEBIMENTOS` DECIMAL(12,2),
  `PAGAMENTOS` DECIMAL(12,2),
  `SALDO_CONTA` DECIMAL(12,2),
  `CHEQUE_NAO_COMPENSADO` DECIMAL(12,2),
  `SALDO_DISPONIVEL` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_EXTRATO_CONTA_BANCO
CREATE TABLE `FIN_EXTRATO_CONTA_BANCO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `MES_ANO` VARCHAR(100),
  `MES` VARCHAR(50),
  `ANO` VARCHAR(50),
  `DATA_MOVIMENTO` DATE,
  `DATA_BALANCETE` DATE,
  `HISTORICO` VARCHAR(100),
  `DOCUMENTO` VARCHAR(100),
  `VALOR` DECIMAL(12,2),
  `CONCILIADO` VARCHAR(50),
  `OBSERVACAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_LANCAMENTO_PAGAR
CREATE TABLE `FIN_LANCAMENTO_PAGAR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_FIN_NATUREZA_FINANCEIRA` INT NOT NULL,
  `ID_FIN_DOCUMENTO_ORIGEM` INT NOT NULL,
  `ID_FORNECEDOR` INT NOT NULL,
  `QUANTIDADE_PARCELA` INT,
  `VALOR_TOTAL` DECIMAL(12,2),
  `VALOR_A_PAGAR` DECIMAL(12,2),
  `DATA_LANCAMENTO` DATE,
  `NUMERO_DOCUMENTO` VARCHAR(100),
  `IMAGEM_DOCUMENTO` TEXT,
  `PRIMEIRO_VENCIMENTO` DATE,
  `INTERVALO_ENTRE_PARCELAS` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_PARCELA_PAGAR
CREATE TABLE `FIN_PARCELA_PAGAR` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `ID_FIN_LANCAMENTO_PAGAR` INT NOT NULL,
  `ID_FIN_STATUS_PARCELA` INT NOT NULL,
  `NUMERO_PARCELA` INT,
  `DATA_EMISSAO` DATE,
  `DATA_VENCIMENTO` DATE,
  `DESCONTO_ATE` DATE,
  `VALOR` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_PARCELA_PAGAMENTO
CREATE TABLE `FIN_PARCELA_PAGAMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_FIN_PARCELA_PAGAR` INT NOT NULL,
  `ID_FIN_CHEQUE_EMITIDO` INT,
  `ID_FIN_TIPO_PAGAMENTO` INT NOT NULL,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `DATA_PAGAMENTO` DATE,
  `TAXA_JURO` DECIMAL(12,2),
  `TAXA_MULTA` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_JURO` DECIMAL(12,2),
  `VALOR_MULTA` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_PAGO` DECIMAL(12,2),
  `HISTORICO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_DOCUMENTO_ORIGEM
CREATE TABLE `FIN_DOCUMENTO_ORIGEM` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(50),
  `SIGLA_DOCUMENTO` VARCHAR(50),
  `DESCRICAO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_STATUS_PARCELA
CREATE TABLE `FIN_STATUS_PARCELA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `SITUACAO` VARCHAR(50) NOT NULL,
  `DESCRICAO` VARCHAR(100),
  `PROCEDIMENTO` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_TIPO_PAGAMENTO
CREATE TABLE `FIN_TIPO_PAGAMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `TIPO` VARCHAR(50),
  `DESCRICAO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_CHEQUE_EMITIDO
CREATE TABLE `FIN_CHEQUE_EMITIDO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CHEQUE` INT NOT NULL,
  `DATA_EMISSAO` DATE,
  `BOM_PARA` DATE,
  `DATA_COMPENSACAO` DATE,
  `VALOR` DECIMAL(12,2),
  `NOMINAL_A` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_TIPO_RECEBIMENTO
CREATE TABLE `FIN_TIPO_RECEBIMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `TIPO` VARCHAR(50),
  `DESCRICAO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_LANCAMENTO_RECEBER
CREATE TABLE `FIN_LANCAMENTO_RECEBER` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_FIN_NATUREZA_FINANCEIRA` INT NOT NULL,
  `ID_FIN_DOCUMENTO_ORIGEM` INT NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  `QUANTIDADE_PARCELA` INT,
  `VALOR_TOTAL` DECIMAL(12,2),
  `VALOR_A_RECEBER` DECIMAL(12,2),
  `DATA_LANCAMENTO` DATE,
  `NUMERO_DOCUMENTO` VARCHAR(100),
  `PRIMEIRO_VENCIMENTO` DATE,
  `TAXA_COMISSAO` DECIMAL(12,2),
  `VALOR_COMISSAO` DECIMAL(12,2),
  `INTERVALO_ENTRE_PARCELAS` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_PARCELA_RECEBER
CREATE TABLE `FIN_PARCELA_RECEBER` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `ID_FIN_LANCAMENTO_RECEBER` INT NOT NULL,
  `ID_FIN_STATUS_PARCELA` INT NOT NULL,
  `NUMERO_PARCELA` INT,
  `DATA_EMISSAO` DATE,
  `DATA_VENCIMENTO` DATE,
  `DESCONTO_ATE` DATE,
  `VALOR` DECIMAL(12,2),
  `EMITIU_BOLETO` VARCHAR(50),
  `BOLETO_NOSSO_NUMERO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_PARCELA_RECEBIMENTO
CREATE TABLE `FIN_PARCELA_RECEBIMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_FIN_PARCELA_RECEBER` INT NOT NULL,
  `ID_FIN_TIPO_RECEBIMENTO` INT NOT NULL,
  `ID_FIN_CHEQUE_RECEBIDO` INT,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `DATA_RECEBIMENTO` DATE,
  `TAXA_JURO` DECIMAL(12,2),
  `TAXA_MULTA` DECIMAL(12,2),
  `TAXA_DESCONTO` DECIMAL(12,2),
  `VALOR_JURO` DECIMAL(12,2),
  `VALOR_MULTA` DECIMAL(12,2),
  `VALOR_DESCONTO` DECIMAL(12,2),
  `VALOR_RECEBIDO` DECIMAL(12,2),
  `HISTORICO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela VENDA_COMISSAO
CREATE TABLE `VENDA_COMISSAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_VENDEDOR` INT NOT NULL,
  `ID_VENDA_CABECALHO` INT NOT NULL,
  `VALOR_VENDA` DECIMAL(12,2),
  `TIPO_CONTABIL` VARCHAR(50),
  `VALOR_COMISSAO` DECIMAL(12,2),
  `SITUACAO` VARCHAR(50),
  `DATA_LANCAMENTO` DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_CHEQUE_RECEBIDO
CREATE TABLE `FIN_CHEQUE_RECEBIDO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_PESSOA` INT,
  `CPF_CNPJ` VARCHAR(100),
  `NOME` VARCHAR(100),
  `CODIGO_BANCO` VARCHAR(100),
  `CODIGO_AGENCIA` VARCHAR(100),
  `CONTA` VARCHAR(100),
  `NUMERO` INT,
  `DATA_EMISSAO` DATE,
  `BOM_PARA` DATE,
  `DATA_COMPENSACAO` DATE,
  `VALOR` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela SITUACAO_DOCUMENTO
CREATE TABLE `SITUACAO_DOCUMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(100),
  `DESCRICAO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela EMPRESA_CNAE
CREATE TABLE `EMPRESA_CNAE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CNAE` INT NOT NULL,
  `ID_EMPRESA` INT NOT NULL,
  `PRINCIPAL` VARCHAR(50),
  `RAMO_ATIVIDADE` VARCHAR(100),
  `OBJETO_SOCIAL` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela REQUISICAO_INTERNA_CABECALHO
CREATE TABLE `REQUISICAO_INTERNA_CABECALHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COLABORADOR` INT NOT NULL,
  `DATA_REQUISICAO` DATE NOT NULL,
  `SITUACAO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela REQUISICAO_INTERNA_DETALHE
CREATE TABLE `REQUISICAO_INTERNA_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_REQ_INTERNA_CABECALHO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE` DECIMAL(12,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ESTOQUE_REAJUSTE_CABECALHO
CREATE TABLE `ESTOQUE_REAJUSTE_CABECALHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_COLABORADOR` INT NOT NULL,
  `DATA_REAJUSTE` DATE,
  `PORCENTAGEM` DECIMAL(12,2),
  `TIPO_REAJUSTE` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ESTOQUE_REAJUSTE_DETALHE
CREATE TABLE `ESTOQUE_REAJUSTE_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_ESTOQUE_REAJUSTE_CABECALHO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `VALOR_ORIGINAL` DECIMAL(12,2),
  `VALOR_REAJUSTE` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ESTOQUE_CONTAGEM_CABECALHO
CREATE TABLE `ESTOQUE_CONTAGEM_CABECALHO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DATA_CONTAGEM` DATE,
  `ESTOQUE_ATUALIZADO` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela ESTOQUE_CONTAGEM_DETALHE
CREATE TABLE `ESTOQUE_CONTAGEM_DETALHE` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_ESTOQUE_CONTAGEM_CABECALHO` INT NOT NULL,
  `ID_PRODUTO` INT NOT NULL,
  `QUANTIDADE_CONTADA` DECIMAL(12,2),
  `QUANTIDADE_SISTEMA` DECIMAL(12,2),
  `ACURACIDADE` DECIMAL(12,2),
  `DIVERGENCIA` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_CONFIGURACAO_BOLETO
CREATE TABLE `FIN_CONFIGURACAO_BOLETO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ID_CONTA_CAIXA` INT NOT NULL,
  `INSTRUCAO01` VARCHAR(100),
  `INSTRUCAO02` VARCHAR(100),
  `CAMINHO_ARQUIVO_REMESSA` VARCHAR(100),
  `CAMINHO_ARQUIVO_RETORNO` VARCHAR(100),
  `CAMINHO_ARQUIVO_LOGOTIPO` VARCHAR(100),
  `CAMINHO_ARQUIVO_PDF` VARCHAR(100),
  `MENSAGEM` VARCHAR(100),
  `LOCAL_PAGAMENTO` VARCHAR(100),
  `LAYOUT_REMESSA` VARCHAR(50),
  `ACEITE` VARCHAR(50),
  `ESPECIE` VARCHAR(50),
  `CARTEIRA` VARCHAR(50),
  `CODIGO_CONVENIO` VARCHAR(100),
  `CODIGO_CEDENTE` VARCHAR(100),
  `TAXA_MULTA` DECIMAL(12,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela MODELO_NOTA_FISCAL
CREATE TABLE `MODELO_NOTA_FISCAL` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(50),
  `DESCRICAO` VARCHAR(100),
  `MODELO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela FIN_NATUREZA_FINANCEIRA
CREATE TABLE `FIN_NATUREZA_FINANCEIRA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CODIGO` VARCHAR(50),
  `DESCRICAO` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Adicionando constraints de chave estrangeira após a criação de todas as tabelas

-- Constraints para a tabela FORNECEDOR
ALTER TABLE `FORNECEDOR` ADD CONSTRAINT `fk_fornecedor_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);
ALTER TABLE `FORNECEDOR` ADD CONSTRAINT `fk_fornecedor_atividade` FOREIGN KEY (`ID_ATIVIDADE_FOR_CLI`) REFERENCES `ATIVIDADE_FOR_CLI` (`ID`);
ALTER TABLE `FORNECEDOR` ADD CONSTRAINT `fk_fornecedor_situacao` FOREIGN KEY (`ID_SITUACAO_FOR_CLI`) REFERENCES `SITUACAO_FOR_CLI` (`ID`);

-- Constraints para a tabela CLIENTE
ALTER TABLE `CLIENTE` ADD CONSTRAINT `fk_cliente_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);
ALTER TABLE `CLIENTE` ADD CONSTRAINT `fk_cliente_atividade` FOREIGN KEY (`ID_ATIVIDADE_FOR_CLI`) REFERENCES `ATIVIDADE_FOR_CLI` (`ID`);
ALTER TABLE `CLIENTE` ADD CONSTRAINT `fk_cliente_situacao` FOREIGN KEY (`ID_SITUACAO_FOR_CLI`) REFERENCES `SITUACAO_FOR_CLI` (`ID`);

-- Constraints para a tabela COLABORADOR
ALTER TABLE `COLABORADOR` ADD CONSTRAINT `fk_colaborador_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);
ALTER TABLE `COLABORADOR` ADD CONSTRAINT `fk_colaborador_tipo` FOREIGN KEY (`ID_TIPO_COLABORADOR`) REFERENCES `TIPO_COLABORADOR` (`ID`);
ALTER TABLE `COLABORADOR` ADD CONSTRAINT `fk_colaborador_cargo` FOREIGN KEY (`ID_CARGO`) REFERENCES `CARGO` (`ID`);
ALTER TABLE `COLABORADOR` ADD CONSTRAINT `fk_colaborador_setor` FOREIGN KEY (`ID_SETOR`) REFERENCES `SETOR` (`ID`);

-- Constraints para a tabela PRODUTO
ALTER TABLE `PRODUTO` ADD CONSTRAINT `fk_produto_unidade` FOREIGN KEY (`ID_UNIDADE_PRODUTO`) REFERENCES `UNIDADE_PRODUTO` (`ID`);
ALTER TABLE `PRODUTO` ADD CONSTRAINT `fk_produto_marca` FOREIGN KEY (`ID_MARCA_PRODUTO`) REFERENCES `PRODUTO_MARCA` (`ID`);
ALTER TABLE `PRODUTO` ADD CONSTRAINT `fk_produto_subgrupo` FOREIGN KEY (`ID_SUB_GRUPO`) REFERENCES `PRODUTO_SUB_GRUPO` (`ID`);

-- Constraints para a tabela UF
ALTER TABLE `UF` ADD CONSTRAINT `fk_uf_pais` FOREIGN KEY (`ID_PAIS`) REFERENCES `PAIS` (`ID`);

-- Constraints para a tabela MUNICIPIO
ALTER TABLE `MUNICIPIO` ADD CONSTRAINT `fk_municipio_uf` FOREIGN KEY (`ID_UF`) REFERENCES `UF` (`ID`);

-- Constraints para a tabela AGENCIA_BANCO
ALTER TABLE `AGENCIA_BANCO` ADD CONSTRAINT `fk_agencia_banco` FOREIGN KEY (`ID_BANCO`) REFERENCES `BANCO` (`ID`);

-- Constraints para a tabela OPERADORA_CARTAO
ALTER TABLE `OPERADORA_CARTAO` ADD CONSTRAINT `fk_operadora_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Constraints para a tabela PRODUTO_SUB_GRUPO
ALTER TABLE `PRODUTO_SUB_GRUPO` ADD CONSTRAINT `fk_subgrupo_grupo` FOREIGN KEY (`ID_GRUPO`) REFERENCES `PRODUTO_GRUPO` (`ID`);

-- Constraints para a tabela CONTATO
ALTER TABLE `CONTATO` ADD CONSTRAINT `fk_contato_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);
ALTER TABLE `CONTATO` ADD CONSTRAINT `fk_contato_empresa` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA` (`ID`);

-- Constraints para a tabela ENDERECO
ALTER TABLE `ENDERECO` ADD CONSTRAINT `fk_endereco_empresa` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA` (`ID`);
ALTER TABLE `ENDERECO` ADD CONSTRAINT `fk_endereco_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);

-- Constraints para a tabela USUARIO
ALTER TABLE `USUARIO` ADD CONSTRAINT `fk_usuario_colaborador` FOREIGN KEY (`ID_COLABORADOR`) REFERENCES `COLABORADOR` (`ID`);
ALTER TABLE `USUARIO` ADD CONSTRAINT `fk_usuario_papel` FOREIGN KEY (`ID_PAPEL`) REFERENCES `PAPEL` (`ID`);

-- Constraints para a tabela PAPEL_FUNCAO
ALTER TABLE `PAPEL_FUNCAO` ADD CONSTRAINT `fk_papelfuncao_papel` FOREIGN KEY (`ID_PAPEL`) REFERENCES `PAPEL` (`ID`);
ALTER TABLE `PAPEL_FUNCAO` ADD CONSTRAINT `fk_papelfuncao_funcao` FOREIGN KEY (`ID_FUNCAO`) REFERENCES `FUNCAO` (`ID`);

-- Constraints para a tabela TRANSPORTADORA
ALTER TABLE `TRANSPORTADORA` ADD CONSTRAINT `fk_transportadora_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);

-- Constraints para a tabela TALONARIO_CHEQUE
ALTER TABLE `TALONARIO_CHEQUE` ADD CONSTRAINT `fk_talao_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Constraints para a tabela CHEQUE
ALTER TABLE `CHEQUE` ADD CONSTRAINT `fk_cheque_talao` FOREIGN KEY (`ID_TALONARIO_CHEQUE`) REFERENCES `TALONARIO_CHEQUE` (`ID`);

-- Constraints para a tabela PESSOA_FISICA
ALTER TABLE `PESSOA_FISICA` ADD CONSTRAINT `fk_pessoafisica_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);
ALTER TABLE `PESSOA_FISICA` ADD CONSTRAINT `fk_pessoafisica_estadocivil` FOREIGN KEY (`ID_ESTADO_CIVIL`) REFERENCES `ESTADO_CIVIL` (`ID`);

-- Constraints para a tabela PESSOA_JURIDICA
ALTER TABLE `PESSOA_JURIDICA` ADD CONSTRAINT `fk_pessoajuridica_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);

-- Constraints para a tabela CONTA_CAIXA
ALTER TABLE `CONTA_CAIXA` ADD CONSTRAINT `fk_conta_agencia` FOREIGN KEY (`ID_AGENCIA_BANCO`) REFERENCES `AGENCIA_BANCO` (`ID`);

-- Constraints para a tabela VENDEDOR
ALTER TABLE `VENDEDOR` ADD CONSTRAINT `fk_vendedor_colaborador` FOREIGN KEY (`ID_COLABORADOR`) REFERENCES `COLABORADOR` (`ID`);

-- Constraints para a tabela COMPRA_REQUISICAO
ALTER TABLE `COMPRA_REQUISICAO` ADD CONSTRAINT `fk_requisicao_tipo` FOREIGN KEY (`ID_COMPRA_TIPO_REQUISICAO`) REFERENCES `COMPRA_TIPO_REQUISICAO` (`ID`);
ALTER TABLE `COMPRA_REQUISICAO` ADD CONSTRAINT `fk_requisicao_colaborador` FOREIGN KEY (`ID_COLABORADOR`) REFERENCES `COLABORADOR` (`ID`);

-- Constraints para a tabela COMPRA_REQUISICAO_DETALHE
ALTER TABLE `COMPRA_REQUISICAO_DETALHE` ADD CONSTRAINT `fk_reqdetalhe_requisicao` FOREIGN KEY (`ID_COMPRA_REQUISICAO`) REFERENCES `COMPRA_REQUISICAO` (`ID`);
ALTER TABLE `COMPRA_REQUISICAO_DETALHE` ADD CONSTRAINT `fk_reqdetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela COMPRA_FORNECEDOR_COTACAO
ALTER TABLE `COMPRA_FORNECEDOR_COTACAO` ADD CONSTRAINT `fk_forneccotacao_cotacao` FOREIGN KEY (`ID_COMPRA_COTACAO`) REFERENCES `COMPRA_COTACAO` (`ID`);
ALTER TABLE `COMPRA_FORNECEDOR_COTACAO` ADD CONSTRAINT `fk_forneccotacao_fornecedor` FOREIGN KEY (`ID_FORNECEDOR`) REFERENCES `FORNECEDOR` (`ID`);

-- Constraints para a tabela COMPRA_COTACAO_DETALHE
ALTER TABLE `COMPRA_COTACAO_DETALHE` ADD CONSTRAINT `fk_cotacaodetalhe_forneccotacao` FOREIGN KEY (`ID_COMPRA_FORNECEDOR_COTACAO`) REFERENCES `COMPRA_FORNECEDOR_COTACAO` (`ID`);
ALTER TABLE `COMPRA_COTACAO_DETALHE` ADD CONSTRAINT `fk_cotacaodetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela COMPRA_REQ_COTACAO_DETALHE
ALTER TABLE `COMPRA_REQ_COTACAO_DETALHE` ADD CONSTRAINT `fk_reqcotdetalhe_cotacao` FOREIGN KEY (`ID_COMPRA_COTACAO`) REFERENCES `COMPRA_COTACAO` (`ID`);
ALTER TABLE `COMPRA_REQ_COTACAO_DETALHE` ADD CONSTRAINT `fk_reqcotdetalhe_reqdetalhe` FOREIGN KEY (`ID_COMPRA_REQUISICAO_DETALHE`) REFERENCES `COMPRA_REQUISICAO_DETALHE` (`ID`);

-- Constraints para a tabela COMPRA_PEDIDO
ALTER TABLE `COMPRA_PEDIDO` ADD CONSTRAINT `fk_pedido_tipo` FOREIGN KEY (`ID_COMPRA_TIPO_PEDIDO`) REFERENCES `COMPRA_TIPO_PEDIDO` (`ID`);
ALTER TABLE `COMPRA_PEDIDO` ADD CONSTRAINT `fk_pedido_fornecedor` FOREIGN KEY (`ID_FORNECEDOR`) REFERENCES `FORNECEDOR` (`ID`);

-- Constraints para a tabela COMPRA_PEDIDO_DETALHE
ALTER TABLE `COMPRA_PEDIDO_DETALHE` ADD CONSTRAINT `fk_pedidodetalhe_pedido` FOREIGN KEY (`ID_COMPRA_PEDIDO`) REFERENCES `COMPRA_PEDIDO` (`ID`);
ALTER TABLE `COMPRA_PEDIDO_DETALHE` ADD CONSTRAINT `fk_pedidodetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela COMPRA_COTACAO_PEDIDO_DETALHE
ALTER TABLE `COMPRA_COTACAO_PEDIDO_DETALHE` ADD CONSTRAINT `fk_cotpeddetalhe_pedido` FOREIGN KEY (`ID_COMPRA_PEDIDO`) REFERENCES `COMPRA_PEDIDO` (`ID`);
ALTER TABLE `COMPRA_COTACAO_PEDIDO_DETALHE` ADD CONSTRAINT `fk_cotpeddetalhe_cotacaodetalhe` FOREIGN KEY (`ID_COMPRA_COTACAO_DETALHE`) REFERENCES `COMPRA_COTACAO_DETALHE` (`ID`);

-- Constraints para a tabela VENDA_ORCAMENTO_CABECALHO
ALTER TABLE `VENDA_ORCAMENTO_CABECALHO` ADD CONSTRAINT `fk_orcamento_condpagto` FOREIGN KEY (`ID_VENDA_CONDICOES_PAGAMENTO`) REFERENCES `VENDA_CONDICOES_PAGAMENTO` (`ID`);
ALTER TABLE `VENDA_ORCAMENTO_CABECALHO` ADD CONSTRAINT `fk_orcamento_vendedor` FOREIGN KEY (`ID_VENDEDOR`) REFERENCES `VENDEDOR` (`ID`);
ALTER TABLE `VENDA_ORCAMENTO_CABECALHO` ADD CONSTRAINT `fk_orcamento_transportadora` FOREIGN KEY (`ID_TRANSPORTADORA`) REFERENCES `TRANSPORTADORA` (`ID`);
ALTER TABLE `VENDA_ORCAMENTO_CABECALHO` ADD CONSTRAINT `fk_orcamento_cliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID`);

-- Constraints para a tabela VENDA_ORCAMENTO_DETALHE
ALTER TABLE `VENDA_ORCAMENTO_DETALHE` ADD CONSTRAINT `fk_orcdetalhe_orcamento` FOREIGN KEY (`ID_VENDA_ORCAMENTO_CABECALHO`) REFERENCES `VENDA_ORCAMENTO_CABECALHO` (`ID`);
ALTER TABLE `VENDA_ORCAMENTO_DETALHE` ADD CONSTRAINT `fk_orcdetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela VENDA_CABECALHO
ALTER TABLE `VENDA_CABECALHO` ADD CONSTRAINT `fk_venda_orcamento` FOREIGN KEY (`ID_VENDA_ORCAMENTO_CABECALHO`) REFERENCES `VENDA_ORCAMENTO_CABECALHO` (`ID`);
ALTER TABLE `VENDA_CABECALHO` ADD CONSTRAINT `fk_venda_condpagto` FOREIGN KEY (`ID_VENDA_CONDICOES_PAGAMENTO`) REFERENCES `VENDA_CONDICOES_PAGAMENTO` (`ID`);
ALTER TABLE `VENDA_CABECALHO` ADD CONSTRAINT `fk_venda_transportadora` FOREIGN KEY (`ID_TRANSPORTADORA`) REFERENCES `TRANSPORTADORA` (`ID`);
ALTER TABLE `VENDA_CABECALHO` ADD CONSTRAINT `fk_venda_tiponota` FOREIGN KEY (`ID_TIPO_NOTA_FISCAL`) REFERENCES `TIPO_NOTA_FISCAL` (`ID`);
ALTER TABLE `VENDA_CABECALHO` ADD CONSTRAINT `fk_venda_cliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID`);
ALTER TABLE `VENDA_CABECALHO` ADD CONSTRAINT `fk_venda_vendedor` FOREIGN KEY (`ID_VENDEDOR`) REFERENCES `VENDEDOR` (`ID`);

-- Constraints para a tabela VENDA_DETALHE
ALTER TABLE `VENDA_DETALHE` ADD CONSTRAINT `fk_vendadetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);
ALTER TABLE `VENDA_DETALHE` ADD CONSTRAINT `fk_vendadetalhe_venda` FOREIGN KEY (`ID_VENDA_CABECALHO`) REFERENCES `VENDA_CABECALHO` (`ID`);

-- Constraints para a tabela VENDA_CONDICOES_PARCELAS
ALTER TABLE `VENDA_CONDICOES_PARCELAS` ADD CONSTRAINT `fk_parcelas_condpagto` FOREIGN KEY (`ID_VENDA_CONDICOES_PAGAMENTO`) REFERENCES `VENDA_CONDICOES_PAGAMENTO` (`ID`);

-- Constraints para a tabela FIN_FECHAMENTO_CAIXA_BANCO
ALTER TABLE `FIN_FECHAMENTO_CAIXA_BANCO` ADD CONSTRAINT `fk_fechamento_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Constraints para a tabela FIN_EXTRATO_CONTA_BANCO
ALTER TABLE `FIN_EXTRATO_CONTA_BANCO` ADD CONSTRAINT `fk_extrato_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Constraints para a tabela FIN_LANCAMENTO_PAGAR
ALTER TABLE `FIN_LANCAMENTO_PAGAR` ADD CONSTRAINT `fk_lancpagto_natureza` FOREIGN KEY (`ID_FIN_NATUREZA_FINANCEIRA`) REFERENCES `FIN_NATUREZA_FINANCEIRA` (`ID`);
ALTER TABLE `FIN_LANCAMENTO_PAGAR` ADD CONSTRAINT `fk_lancpagto_docorigem` FOREIGN KEY (`ID_FIN_DOCUMENTO_ORIGEM`) REFERENCES `FIN_DOCUMENTO_ORIGEM` (`ID`);
ALTER TABLE `FIN_LANCAMENTO_PAGAR` ADD CONSTRAINT `fk_lancpagto_fornecedor` FOREIGN KEY (`ID_FORNECEDOR`) REFERENCES `FORNECEDOR` (`ID`);

-- Constraints para a tabela FIN_PARCELA_PAGAR
ALTER TABLE `FIN_PARCELA_PAGAR` ADD CONSTRAINT `fk_parcelapagar_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);
ALTER TABLE `FIN_PARCELA_PAGAR` ADD CONSTRAINT `fk_parcelapagar_lancamento` FOREIGN KEY (`ID_FIN_LANCAMENTO_PAGAR`) REFERENCES `FIN_LANCAMENTO_PAGAR` (`ID`);
ALTER TABLE `FIN_PARCELA_PAGAR` ADD CONSTRAINT `fk_parcelapagar_status` FOREIGN KEY (`ID_FIN_STATUS_PARCELA`) REFERENCES `FIN_STATUS_PARCELA` (`ID`);

-- Constraints para a tabela FIN_PARCELA_PAGAMENTO
ALTER TABLE `FIN_PARCELA_PAGAMENTO` ADD CONSTRAINT `fk_pagamento_parcela` FOREIGN KEY (`ID_FIN_PARCELA_PAGAR`) REFERENCES `FIN_PARCELA_PAGAR` (`ID`);
ALTER TABLE `FIN_PARCELA_PAGAMENTO` ADD CONSTRAINT `fk_pagamento_cheque` FOREIGN KEY (`ID_FIN_CHEQUE_EMITIDO`) REFERENCES `FIN_CHEQUE_EMITIDO` (`ID`);
ALTER TABLE `FIN_PARCELA_PAGAMENTO` ADD CONSTRAINT `fk_pagamento_tipo` FOREIGN KEY (`ID_FIN_TIPO_PAGAMENTO`) REFERENCES `FIN_TIPO_PAGAMENTO` (`ID`);
ALTER TABLE `FIN_PARCELA_PAGAMENTO` ADD CONSTRAINT `fk_pagamento_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Constraints para a tabela FIN_CHEQUE_EMITIDO
ALTER TABLE `FIN_CHEQUE_EMITIDO` ADD CONSTRAINT `fk_chequeemitido_cheque` FOREIGN KEY (`ID_CHEQUE`) REFERENCES `CHEQUE` (`ID`);

-- Constraints para a tabela FIN_LANCAMENTO_RECEBER
ALTER TABLE `FIN_LANCAMENTO_RECEBER` ADD CONSTRAINT `fk_lancreceber_natureza` FOREIGN KEY (`ID_FIN_NATUREZA_FINANCEIRA`) REFERENCES `FIN_NATUREZA_FINANCEIRA` (`ID`);
ALTER TABLE `FIN_LANCAMENTO_RECEBER` ADD CONSTRAINT `fk_lancreceber_docorigem` FOREIGN KEY (`ID_FIN_DOCUMENTO_ORIGEM`) REFERENCES `FIN_DOCUMENTO_ORIGEM` (`ID`);
ALTER TABLE `FIN_LANCAMENTO_RECEBER` ADD CONSTRAINT `fk_lancreceber_cliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`ID`);

-- Constraints para a tabela FIN_PARCELA_RECEBER
ALTER TABLE `FIN_PARCELA_RECEBER` ADD CONSTRAINT `fk_parcelareceber_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);
ALTER TABLE `FIN_PARCELA_RECEBER` ADD CONSTRAINT `fk_parcelareceber_lancamento` FOREIGN KEY (`ID_FIN_LANCAMENTO_RECEBER`) REFERENCES `FIN_LANCAMENTO_RECEBER` (`ID`);
ALTER TABLE `FIN_PARCELA_RECEBER` ADD CONSTRAINT `fk_parcelareceber_status` FOREIGN KEY (`ID_FIN_STATUS_PARCELA`) REFERENCES `FIN_STATUS_PARCELA` (`ID`);

-- Constraints para a tabela FIN_PARCELA_RECEBIMENTO
ALTER TABLE `FIN_PARCELA_RECEBIMENTO` ADD CONSTRAINT `fk_recebimento_parcela` FOREIGN KEY (`ID_FIN_PARCELA_RECEBER`) REFERENCES `FIN_PARCELA_RECEBER` (`ID`);
ALTER TABLE `FIN_PARCELA_RECEBIMENTO` ADD CONSTRAINT `fk_recebimento_tipo` FOREIGN KEY (`ID_FIN_TIPO_RECEBIMENTO`) REFERENCES `FIN_TIPO_RECEBIMENTO` (`ID`);
ALTER TABLE `FIN_PARCELA_RECEBIMENTO` ADD CONSTRAINT `fk_recebimento_cheque` FOREIGN KEY (`ID_FIN_CHEQUE_RECEBIDO`) REFERENCES `FIN_CHEQUE_RECEBIDO` (`ID`);
ALTER TABLE `FIN_PARCELA_RECEBIMENTO` ADD CONSTRAINT `fk_recebimento_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Constraints para a tabela VENDA_COMISSAO
ALTER TABLE `VENDA_COMISSAO` ADD CONSTRAINT `fk_comissao_vendedor` FOREIGN KEY (`ID_VENDEDOR`) REFERENCES `VENDEDOR` (`ID`);
ALTER TABLE `VENDA_COMISSAO` ADD CONSTRAINT `fk_comissao_venda` FOREIGN KEY (`ID_VENDA_CABECALHO`) REFERENCES `VENDA_CABECALHO` (`ID`);

-- Constraints para a tabela FIN_CHEQUE_RECEBIDO
ALTER TABLE `FIN_CHEQUE_RECEBIDO` ADD CONSTRAINT `fk_chequerecebido_pessoa` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA` (`ID`);

-- Constraints para a tabela EMPRESA_CNAE
ALTER TABLE `EMPRESA_CNAE` ADD CONSTRAINT `fk_empresacnae_cnae` FOREIGN KEY (`ID_CNAE`) REFERENCES `CNAE` (`ID`);
ALTER TABLE `EMPRESA_CNAE` ADD CONSTRAINT `fk_empresacnae_empresa` FOREIGN KEY (`ID_EMPRESA`) REFERENCES `EMPRESA` (`ID`);

-- Constraints para a tabela REQUISICAO_INTERNA_CABECALHO
ALTER TABLE `REQUISICAO_INTERNA_CABECALHO` ADD CONSTRAINT `fk_reqinterna_colaborador` FOREIGN KEY (`ID_COLABORADOR`) REFERENCES `COLABORADOR` (`ID`);

-- Constraints para a tabela REQUISICAO_INTERNA_DETALHE
ALTER TABLE `REQUISICAO_INTERNA_DETALHE` ADD CONSTRAINT `fk_reqinternadetalhe_reqinterna` FOREIGN KEY (`ID_REQ_INTERNA_CABECALHO`) REFERENCES `REQUISICAO_INTERNA_CABECALHO` (`ID`);
ALTER TABLE `REQUISICAO_INTERNA_DETALHE` ADD CONSTRAINT `fk_reqinternadetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela ESTOQUE_REAJUSTE_CABECALHO
ALTER TABLE `ESTOQUE_REAJUSTE_CABECALHO` ADD CONSTRAINT `fk_reajuste_colaborador` FOREIGN KEY (`ID_COLABORADOR`) REFERENCES `COLABORADOR` (`ID`);

-- Constraints para a tabela ESTOQUE_REAJUSTE_DETALHE
ALTER TABLE `ESTOQUE_REAJUSTE_DETALHE` ADD CONSTRAINT `fk_reajustedetalhe_reajuste` FOREIGN KEY (`ID_ESTOQUE_REAJUSTE_CABECALHO`) REFERENCES `ESTOQUE_REAJUSTE_CABECALHO` (`ID`);
ALTER TABLE `ESTOQUE_REAJUSTE_DETALHE` ADD CONSTRAINT `fk_reajustedetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela ESTOQUE_CONTAGEM_DETALHE
ALTER TABLE `ESTOQUE_CONTAGEM_DETALHE` ADD CONSTRAINT `fk_contagemdetalhe_contagem` FOREIGN KEY (`ID_ESTOQUE_CONTAGEM_CABECALHO`) REFERENCES `ESTOQUE_CONTAGEM_CABECALHO` (`ID`);
ALTER TABLE `ESTOQUE_CONTAGEM_DETALHE` ADD CONSTRAINT `fk_contagemdetalhe_produto` FOREIGN KEY (`ID_PRODUTO`) REFERENCES `PRODUTO` (`ID`);

-- Constraints para a tabela FIN_CONFIGURACAO_BOLETO
ALTER TABLE `FIN_CONFIGURACAO_BOLETO` ADD CONSTRAINT `fk_configboleto_conta` FOREIGN KEY (`ID_CONTA_CAIXA`) REFERENCES `CONTA_CAIXA` (`ID`);

-- Ativando novamente as verificações de chave estrangeira
SET FOREIGN_KEY_CHECKS = 1;
